exchange:
  J:   1e-9                   # [eV]

hyperfine:
  Aa1: 5.2e-8                 # [eV]  
  Ab1: 1.9e-7                 # [eV]  
  Aa2: 3.7e-8                 # [eV]  
  Ab2: 1.0e-7                 # [eV] 

zeeman:
  B0:   0.00                  # [G]    
  g_e:  2.002319              # dimensionless
  g_n1: -1.110104             # dimensionless
  g_n2:  1.404738             # dimensionless
  mu_B: 5.7883818e-09         # [eV/G]
  mu_N: 3.1524512e-12         # [eV/G]

zfs:
  D1: 1e-9                    # [eV]
  D2: 1e-12                   # [eV]

microwave:
  nu:     2.00098e8           # [Hz]   
  omega1: 2.00e5              # [Hz]   

constants:
  h:     4.135667662e-15      # [eVs]
  hbar:  6.58211e-16          # [eVs]

sle:
  k_S: 1e5                    # [Hz]
  k_D: 1e6                    # [Hz]
  p:   1e3                    # dimensionless

lockin: 
  f_mod: 1e3                  # [Hz]
  B_mod: 2                    # [G pp]
